name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Welcome to my first GitHub Action workflow!"
      - name: Print goodbye
        run: |
          echo "It's time to say goodbye!"
          echo "Done - bye!"
